#!/bin/bash
# pactrak
# Keeps a list of installed packages in a Gist at your GitHub account.

pactrak_install(){
    echo "A list of installed packages will be automatically maintained"
    echo "by pactrak in a private Gist at your GitHub account."

    echo -e "\n- Step 1: Log in to Gist using your GitHub account:"
    [[ -f ~/.gist ]] || gist --login
    mkdir -p /root
    cp -v ~/.gist /root/.gist

    echo -e "\n- Step 2: Save list of currently installed packages to Gist:"
    GIST_URL=$(
        (
            pacman -Qn
            echo
            pacman -Qm
        ) | gist -p -f $HOSTNAME.pactrak -d "$HOSTNAME: List of installed packages"
    )

    echo "GIST_ID=$GIST_URL" | sed 's/https:\/\/gist.github.com\///g' >> /etc/pactrak

    echo "An automatically mantained list of installed packages"
    echo "has been successfully created in your GitHub Gist."
    echo "Visit https://gist.github.com or the direct link below:"
    echo "$GIST_URL"
}

pactrak_update(){
    if (pacman -Qn; echo; pacman -Qm) | gist -u "$GIST_ID" -f $HOSTNAME.pactrak; then
        echo "pactrak: Gist successfully updated."
    else
        echo "pactrak: ERROR! Try running"
        echo "sudo gist --login"
    fi
}

# Add Ruby to PATH
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

# Load config
[[ -r '/etc/pactrak' ]] && source /etc/pactrak

# Determine if fresh install is needed
if [ -z "$GIST_ID" ]; then
    echo "Info: Gist is not set up for pactrak."
    echo "Reinstalling pactrak can solve this issue."
    pactrak_install
else
    pactrak_update
fi
